Traceback (most recent call last):
  File "/home/simon/.cache/pypoetry/virtualenvs/pymedphys-OJ9w3Q6B-py3.9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/simon/.cache/pypoetry/virtualenvs/pymedphys-OJ9w3Q6B-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/simon/.cache/pypoetry/virtualenvs/pymedphys-OJ9w3Q6B-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/simon/.cache/pypoetry/virtualenvs/pymedphys-OJ9w3Q6B-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/simon/.asdf/installs/python/3.9.2/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/simon/.cache/pypoetry/virtualenvs/pymedphys-OJ9w3Q6B-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/simon/.cache/pypoetry/virtualenvs/pymedphys-OJ9w3Q6B-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/simon/.cache/pypoetry/virtualenvs/pymedphys-OJ9w3Q6B-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
!pip install pydicom pymedphys

import pydicom
import pymedphys
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-2-89c05e3ae45f>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0;32mimport[0m [0mpydicom[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0;32mimport[0m [0mpymedphys[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mModuleNotFoundError[0m: No module named 'pymedphys'
ModuleNotFoundError: No module named 'pymedphys'

